### ISSUE TITLE
datafunk fails with biopython >1.77

### ISSUE THREAD

**Issue by dfornika** [jts/ncov-tools#40]
I'm seeing this failure on a recently-installed `ncov-qc` conda environment:
```
Traceback (most recent call last):
  File "/home/covid19.analysis/.conda/envs/ncov-qc/bin/datafunk", line 5, in <module>
    from datafunk.__main__ import main
  File "/home/covid19.analysis/.conda/envs/ncov-qc/lib/python3.6/site-packages/datafunk/__init__.py", line 16, in <module>
    from datafunk import *
  File "/home/covid19.analysis/.conda/envs/ncov-qc/lib/python3.6/site-packages/datafunk/get_CDS.py", line 3, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/covid19.analysis/.conda/envs/ncov-qc/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
[Tue Sep 15 11:57:31 2020]
Error in rule datafunk_trim_and_pad:
    jobid: 4
    output: /tmp/tmpo_nwgu6f/post_qc_query.aligned.fasta
    shell:
        
        datafunk sam_2_fasta           -s /tmp/tmpo_nwgu6f/reference_mapped.sam           -r /home/covid19.analysis/.conda/envs/ncov-qc/lib/python3.6/site-packages/pangolin/data/reference.fasta           -o /tmp/tmpo_nwgu6f/post_qc_query.aligned.fasta           -t [265:29674]           --pad           --log-inserts 
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
[Tue Sep 15 11:57:31 2020]
Error in rule make_lineage_assignments:
    jobid: 36
    output: lineages/test_lineage_report.csv
    shell:
        pangolin -t 32 --outfile lineages/test_lineage_report.csv qc_analysis/test_consensus.fasta
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

This seems to be related to a change that was made in biopython v1.78, where the `Bio.Alphabet` module was removed or deprecated:

https://github.com/biopython/biopython/blob/master/NEWS.rst#4-september-2020-biopython-178

I've been able to address this issue by downgrading biopython to v1.77.

Maybe this should also be addressed more directly by adjusting the way that biopython is pinned in datafunk's `setup.py` file, but I'm not sure that would fix things here, since we're using conda to install biopython and pip to install datafunk.

Can I suggest that biopython is pinned to v1.77 in the ncov-tools `environment.yaml` file?

**Comment by rdeborja** [comment]
Thanks Dan, will update the `environment.yaml` file (as you suggested) test and push out.

**Comment by jts** [comment]
PR merged, thanks Dan
